default['reprepro']['fqdn'] = node['fqdn']
default['reprepro']['listen_port'] = 80
default['reprepro']['repo_dir'] = "/srv/apt"
default['reprepro']['incoming'] = "/srv/apt_incoming"
default['reprepro']['distributions'] = {}
default['reprepro']['allow'] = []
default['reprepro']['pulls'] = {}
default['reprepro']['architectures'] = %w(i386 amd64)
default['reprepro']['components'] = ["main"]
default['reprepro']['gnupg_home'] = '/root/.gnupg'
default['reprepro']['enable_repository_on_host'] = false
default['reprepro']['disable_databag'] = false
